# https://www.npmjs.com/package/yourl
# version: 1.0.6+

# 临时项目链接集合配置示例
# 格式【alisa：链接数据项（链接字符串|链接对象|链接数组字符串|链接数组对象）】
bd: http://www.baidu.com
ali:
  title: 阿里巴巴官网
  url: http://www.alibaba.com
bat:
  - http://www.baidu.com
  - http://www.alibaba.com
  - http://www.tencent.com
BAT:
  - title: 百度官网
    url: http://www.baidu.com
  - title: 阿里巴巴官网
    url: http://www.alibaba.com
  - title: 腾讯官网
    url: http://www.tencent.com
#
# 链接集合数据读取后数据结构转换如下：
# {
#   bd: 'http://www.baidu.com',
#   ali: { title: '阿里巴巴官网', url: 'http://www.alibaba.com' },
#   bat: [
#     'http://www.baidu.com',
#     'http://www.alibaba.com',
#     'http://www.tencent.com'
#   ],
#   BAT: [
#     { title: '百度官网', url: 'http://www.baidu.com' },
#     { title: '阿里巴巴官网', url: 'http://www.alibaba.com' },
#     { title: '腾讯官网', url: 'http://www.tencent.com' }
#   ]
# }

# 命令运行说明
#
# 单独打开百度官网
# yl bd
#
# 单独打开阿里巴巴官网
# yl ali
#
# 批量打开BAT三个网站
# yl bat
#   or
# yl BAT
